### ISSUE TITLE
font

### ISSUE THREAD

**Issue by pouyarezaei** [SeedPuller/Boostan-Desktop#4]
change interview page font and application font to [vazir](https://rastikerdar.github.io/vazir-font/)
most of persian based applications use vazir font.
its user friendly

**Comment by SeedPuller** [comment]
We are already using Vazir font.

Boostan gh-page source:
https://github.com/SeedPuller/Boostan-Desktop/blob/gh-pages/assets/style/font.css

Boostan application source:
https://github.com/SeedPuller/Boostan-Desktop/blob/master/qml/main.qml#L19
